---
title: "Counterfactual"
bibliography: ../references.bib
---

Implicit in estimating the relationship of firm production on the environment, we require a means to determining the counterfactual state underwhich the firm is either not dependent or does not impact the environment. 
The current corralary measure for corporate environmental sustainabiility are the ESG scores reported by [Morningstar](https://www.morningstar.com/products/esg-reporting).
In that setting, the counterfactual is a one unit decrease in the firm's ESG score along a 10 point scale. E.g., the counterfactual state is a decile reduction of the environmental impact of the firm. 

For the Matrix, we consider both dependencies and impacts. It is unrelastic to consider that a firm would entirely remove themselves from their environmental relationship. 
So the counterfactual cannot be the impact on the environment in the absence of the firm, nor the impact on the firm in the absence of environmental interaction. 
Rather, we consider two possible counterfactual states. 

# Industry Shifts

In each industry, there is both regulatory standards as well as technological advancements which drive the production function. 
Both determine the reliance on the natural world as well as the generated by-products that impact the natural world. 
A reasonable counterfactual would be to simulate changes in industry standards -- either tighting or loosening standards. 
To ground this in reality, we collect a series of industry standards and technologies in under [Industry Policy](./policy_industry.qmd)

# Place-based Policy Shifts

A second consideration is that firms are non-randomly selecting where production operations occur. This is both a function of natural resource reliance which is spatially varied, as well as the economic incentives of local/regional/national policies. 
A reasonable counterfactual would be to simulate changes in the place-based production standards related to an industry. 
To ground this in reality, we collect a series of place-based standards and economic incentives in under [Place-based Policy](./policy_place.qmd)